name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: pod install
      run: pod install
    - name: Run tests
      run: xcodebuild -workspace quickcodes.xcworkspace -scheme quickcodes -sdk macosx10.15 -destination 'platform=macOS' test
    - name: Archive
      run: xcodebuild -workspace quickcodes.xcworkspace -scheme quickcodes -sdk macosx10.15 -destination 'platform=macOS' archive
    - uses: actions/upload-artifact@v2
      with:
        name: latest-build-release
        path: build/Release/quickcodes.app
