name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: pod install
      run: pod install
    - name: Run tests
      run: xcodebuild -workspace quickcodes.xcworkspace -scheme quickcodes -sdk macosx10.15 -destination 'platform=macOS' test
    - name: Archive
      run: xcodebuild -workspace quickcodes.xcworkspace -scheme quickcodes -sdk macosx10.15 -destination 'platform=macOS' -archivePath quickcodes archive
    - uses: papeloto/action-zip@v1
      with:
        files: quickcodes.xcarchive/Products/Applications/.
        dest: quickcodes.app.zip
    - name: Upload build
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: latest-build-release
        path: quickcodes.app.zip
